#!/bin/bash -xv

###############################################################################
export PROJECT_NAME=OpenMAMA-zmq
export PROJECT_VERSION=2.0
export JIRA_RELEASE=BUS-1780           # release artifact in jira

# internal dependencies
export LIBZMQ_VERSION=4.3.0
export OPENMAMA_VERSION=6.2.1
