#!/bin/bash


OPENMAMA_INSTALL=${INSTALL_BASE}/OpenMAMA/${OPENMAMA_VERSION}/${BUILD_TYPE}
OPENMAMA_SOURCE=${OPENMAMA_INSTALL}/src
LIBZMQ_INSTALL=${INSTALL_BASE}/libzmq/${LIBZMQ_VERSION}/${BUILD_TYPE}
OPENMAMA_OMNM_INSTALL=${INSTALL_BASE}/OpenMAMA-omnm/${OPENMAMA_OMNM_VERSION}/${BUILD_TYPE}
