#!/bin/bash

# libzmq
LIBZMQ_INSTALL=${INSTALL_BASE}/libzmq/${LIBZMQ_VERSION}/${BUILD_TYPE}
export LD_LIBRARY_PATH=${LIBZMQ_INSTALL}/lib64:$LD_LIBRARY_PATH

# OpenMAMA
OPENMAMA_INSTALL=${INSTALL_BASE}/OpenMAMA/${OPENMAMA_VERSION}/${BUILD_TYPE}
export PATH=$OPENMAMA_INSTALL/bin:$PATH
export LD_LIBRARY_PATH=${OPENMAMA_INSTALL}/lib:$LD_LIBRARY_PATH

# OMNM
OPENMAMA_OMNM_INSTALL=${INSTALL_BASE}/OpenMAMA-omnm/${OPENMAMA_OMNM_VERSION}/${BUILD_TYPE}
export LD_LIBRARY_PATH=${OPENMAMA_OMNM_INSTALL}/lib:$LD_LIBRARY_PATH

# OpenMAMA-zmq
OPENMAMA_ZMQ_INSTALL=${INSTALL_BASE}/OpenMAMA-zmq/${OPENMAMA_OMNM_VERSION}/${BUILD_TYPE}
export PATH=${OPENMAMA_ZMQ_INSTALL}/bin:$PATH
export LD_LIBRARY_PATH=${OPENMAMA_ZMQ_INSTALL}/lib:$LD_LIBRARY_PATH


